---

- name: Create Deployment Configuration for Microservice
  hosts: all
  
  tasks:
    - name: Check if Working Folder exist
      stat:
       path: "{{ target }}"
      register: workingDir
 
    - name: create folders for Environment
      file: 
        path: "{{ target }}/{{ item.name }}"
        state: directory
        mode: 0755
      with_items: "{{ environments }}"

    - name: create docker latest  tag folder 
      file: 
        path: "{{ target }}/{{ item.name }}/latest_deployed_docker_image_tags"
        state: directory
        mode: 0755
      with_items: "{{ environments }}"

    - name: create docker override_var folder 
      file: 
        path: "{{ target }}/{{ item.name }}/override_var"
        state: directory
        mode: 0755
      with_items: "{{ environments }}"

    - name: copy microservice properties file for docker tag
      template: 
        src: micro-service-dockertag.properties.j2 
        dest:  "{{ target }}/{{ item.name }}/latest_deployed_docker_image_tags/{{ servicename }}.properties"
      with_items: "{{ environments }}"
    
    - name: copy microservice properties file for docker tag
      template: 
        src: micro-service-override.properties.j2
        dest:  "{{ target }}/{{ item.name }}/override_var/{{ servicename }}.properties"
      with_items: "{{ environments }}"
      
    - name: create folders for Environment
      file: 
        path: "{{ target }}/../../{{ servicename }}/app"
        state: directory
        mode: 0755
    
    - name: Copy deployment.json
      template: 
        src: deployment.json.j2 
        dest:  "/{{ target }}/../../{{ servicename }}/app/deployment.json"
      
    - name: Copy service.json
      template: 
        src: service.json.j2
        dest:  "/{{ target }}/../../{{ servicename }}/app/service.json"